/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppKbNewRouteImport } from './routes/_app/kb.new'
import { Route as AppKbKbIdRouteImport } from './routes/_app/kb.$kbId'
import { Route as AppKbKbIdChatConversationIdRouteImport } from './routes/_app/kb.$kbId/chat.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppKbNewRoute = AppKbNewRouteImport.update({
  id: '/kb/new',
  path: '/kb/new',
  getParentRoute: () => AppRoute,
} as any)
const AppKbKbIdRoute = AppKbKbIdRouteImport.update({
  id: '/kb/$kbId',
  path: '/kb/$kbId',
  getParentRoute: () => AppRoute,
} as any)
const AppKbKbIdChatConversationIdRoute =
  AppKbKbIdChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AppKbKbIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/kb/$kbId': typeof AppKbKbIdRouteWithChildren
  '/kb/new': typeof AppKbNewRoute
  '/kb/$kbId/chat/$conversationId': typeof AppKbKbIdChatConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/kb/$kbId': typeof AppKbKbIdRouteWithChildren
  '/kb/new': typeof AppKbNewRoute
  '/kb/$kbId/chat/$conversationId': typeof AppKbKbIdChatConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/kb/$kbId': typeof AppKbKbIdRouteWithChildren
  '/_app/kb/new': typeof AppKbNewRoute
  '/_app/kb/$kbId/chat/$conversationId': typeof AppKbKbIdChatConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/kb/$kbId'
    | '/kb/new'
    | '/kb/$kbId/chat/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/kb/$kbId'
    | '/kb/new'
    | '/kb/$kbId/chat/$conversationId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/kb/$kbId'
    | '/_app/kb/new'
    | '/_app/kb/$kbId/chat/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/kb/new': {
      id: '/_app/kb/new'
      path: '/kb/new'
      fullPath: '/kb/new'
      preLoaderRoute: typeof AppKbNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kb/$kbId': {
      id: '/_app/kb/$kbId'
      path: '/kb/$kbId'
      fullPath: '/kb/$kbId'
      preLoaderRoute: typeof AppKbKbIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kb/$kbId/chat/$conversationId': {
      id: '/_app/kb/$kbId/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/kb/$kbId/chat/$conversationId'
      preLoaderRoute: typeof AppKbKbIdChatConversationIdRouteImport
      parentRoute: typeof AppKbKbIdRoute
    }
  }
}

interface AppKbKbIdRouteChildren {
  AppKbKbIdChatConversationIdRoute: typeof AppKbKbIdChatConversationIdRoute
}

const AppKbKbIdRouteChildren: AppKbKbIdRouteChildren = {
  AppKbKbIdChatConversationIdRoute: AppKbKbIdChatConversationIdRoute,
}

const AppKbKbIdRouteWithChildren = AppKbKbIdRoute._addFileChildren(
  AppKbKbIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppKbKbIdRoute: typeof AppKbKbIdRouteWithChildren
  AppKbNewRoute: typeof AppKbNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppKbKbIdRoute: AppKbKbIdRouteWithChildren,
  AppKbNewRoute: AppKbNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
